name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Release Files
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Output Release Directory
        run: |
          echo "Listing release directory:"
          ls -R release/

      # 添加重命名Windows zip文件的步骤
      - name: Rename Windows zip
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $zipFile = Get-ChildItem -Path release/*/*.zip | Select-Object -First 1
          if ($zipFile) {
            $newName = $zipFile.FullName -replace '\.zip$', '_portable.zip'
            Rename-Item -Path $zipFile.FullName -NewName $newName
            echo "Renamed zip file to: $newName"
          }

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/*/*.exe
            release/*/*.zip
            release/*/*.blockmap
            release/*/*.dmg
          fail_on_unmatched_files: false
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}