name: Build and Release

on:
  push:
    tags:
      - 'v*' # 当推送以 v 开头的标签时触发

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build Release Files
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: List Release Directory
        run: ls -R release

      - name: Prepare Release Files
        id: prepare_files
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          FILES=$(ls release/$VERSION/*.exe release/$VERSION/*.zip release/$VERSION/*.blockmap release/$VERSION/mac-arm64/nvm-manager.app 2>/dev/null)
          echo "files=$FILES" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.files }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
